## 1. Gram-Schmidt 

In [1]:
import numpy as np
import numpy.linalg as la

tol = 1e-14 # That's 1×10⁻¹⁴ = 0.00000000000001

# Our first function will perform the Gram-Schmidt procedure for 4 basis vectors.
# Go through the vectors one at a time and set them to be orthogonal
# to all the vectors that came before it. 
# Normalising or making it unit vector.

def orthoBasis4(A) :
    B = np.array(A,dtype=np.float_) 
    # First column is easy.. just normalise it. I.e. divide by its norm.
    B[:, 0] = B[:, 0] / la.norm(B[:, 0])
    # For second column, we need to subtract the projection of the first vector on the second
    B[:, 1] = B[:, 1] - B[:, 1] @ B[:, 0] * B[:, 0]
    # Note that if it is non zero, then B[:, 1] is linearly independant of B[:, 0]
    # If this is the case, we can normalise it. Otherwise we'll set that vector to zero.
    if la.norm(B[:, 1]) > tol :
        B[:, 1] = B[:, 1] / la.norm(B[:, 1])
    else :
        B[:, 1] = np.zeros_like(B[:, 1]) #zeros_like is similar to np.zeros but uses the dimension of input array
    # Now we need to repeat the process for remaining columns
    # Insert your code here. you can do it in 2 lines or one line
    # Again we'll need to normalise our new vector.
    # Repeat what we had done earlier
    
        B[:, 2] = B[:, 2] - B[:, 2] @ B[:, 0] * B[:, 0] - B[:, 2] @ B[:, 1] * B[:, 1]
        B[:, 2] = B[:, 2] / la.norm(B[:, 2]) if la.norm(B[:, 2]) > tol else np.zeros_like(B[:, 2])
    
    
    # Finally, column three:
    # Insert your code here. either one line or three lines
    
        B[:, 3] = B[:, 3] - B[:, 3] @ B[:, 0] * B[:, 0] - B[:, 3] @ B[:, 1] * B[:, 1] - B[:, 3] @ B[:, 2] * B[:, 2]
        B[:, 3] = B[:, 3] / la.norm(B[:, 3]) if la.norm(B[:, 3]) > tol else np.zeros_like(B[:, 3])
    
    # Now normalise if possible
    
    # Finally, we return the result:
    return B

# Exploit the repetition in the above code to generalize the function for any given matrix
def orthoBasis(A) :
    B = np.array(A, dtype=np.float_) 
    # Loop over all vectors, starting with zero, label them with i
    for i in range(B.shape[1]) :
        # Inside that loop, loop over all previous vectors, j, to subtract.
        for j in range(i) :
            # Complete the code
            
             B[:, i] = B[:, i] - B[:, i] @ B[:, j] * B[:, j]
        if la.norm(B[:, i]) > tol :
            B[:, i] = B[:, i] / la.norm(B[:, i])
        else :
            B[:, i] = np.zeros_like(B[:, i])
            
        # Next insert code to do the normalisation test for B[:, i]
        
        B[:, i] = B[:, i] - B[:, i] @ B[:, j] * B[:, j]
        B[:, i] = B[:, i] / la.norm(B[:, i]) if la.norm(B[:, i]) > tol else np.zeros_like(B[:, i])
            
    # Finally, we return the result:
    
    return B



## 2. PageRank


In [66]:
import numpy as np
import numpy.linalg as la
np.set_printoptions(suppress=True)

### PageRank as a linear algebra problem
Let's imagine a micro-internet, with just 6 websites 
Each website links to some of the others, and this forms a network as shown,

![A Micro-Internet](internet_1.png "A Micro-Internet")


Imagine 100s of a person P on our micro-internet, each viewing a single website at a time.
Each minute P follow a link on their website to another site on the micro-internet.
After a while, the websites that are most linked to will have more Ps visiting them, and in the long run, each minute for every P that leaves a website, another will enter keeping the total numbers of Ps on each website constant.
The PageRank is simply the ranking of websites by how many Ps they have on them at the end of this process.

We represent the number of Ps on each website with the vector,
$$\mathbf{r} = \begin{bmatrix} r_A \\ r_B \\ r_C \\ r_D \\ r_E \\ r_F \end{bmatrix}$$
And say that the number of Ps on each website in minute $i+1$ is related to those at minute $i$ by the matrix transformation

$$ \mathbf{r}^{(i+1)} = L \,\mathbf{r}^{(i)}$$
with the matrix $L$ taking the form,
$$ L = \begin{bmatrix}
L_{A→A} & L_{B→A} & L_{C→A} & L_{D→A} & L_{E→A} & L_{F→A} \\
L_{A→B} & L_{B→B} & L_{C→B} & L_{D→B} & L_{E→B} & L_{F→B} \\
L_{A→C} & L_{B→C} & L_{C→C} & L_{D→C} & L_{E→C} & L_{F→C} \\
L_{A→D} & L_{B→D} & L_{C→D} & L_{D→D} & L_{E→D} & L_{F→D} \\
L_{A→E} & L_{B→E} & L_{C→E} & L_{D→E} & L_{E→E} & L_{F→E} \\
L_{A→F} & L_{B→F} & L_{C→F} & L_{D→F} & L_{E→F} & L_{F→F} \\
\end{bmatrix}
$$
where the columns represent the probability of leaving a website for any other website, and sum to one.
The rows determine how likely you are to enter a website from any other, though these need not add to one.
The long time behaviour of this system is when $ \mathbf{r}^{(i+1)} = \mathbf{r}^{(i)}$, so we'll drop the superscripts here, and that allows us to write,
$$ L \,\mathbf{r} = \mathbf{r}$$

which is an eigenvalue equation for the matrix $L$, with eigenvalue 1 (this is guaranteed by the probabalistic structure of the matrix $L$).

Complete the matrix $L$ below.

In [37]:
# Replace the ??? here with the probability of clicking a link to each website.
L = np.array([[0,   1/2, 1/3,  0,  0,      0],
              [1/3,  0,   0,    0,  1/2,    0],   
              [1/3,  1/2, 0,    1,  0,    1/2],
              [1/3,  0,   1/3,  0,  1/2,  1/2],
              [0,    0,   0,    0,  0,      0],
              [0,    0,   1/3,  0,  0,      0]])

In [38]:
eVals, eVecs = la.eig(L) # Gets the eigenvalues and vectors
order = np.absolute(eVals).argsort()[::-1] # Orders them by their eigenvalues
eVals = eVals[order]
eVecs = eVecs[:,order]

r = eVecs[:, 0] # Sets r to be the principal eigenvector
100 * np.real(r / np.sum(r)) # Make this eigenvector sum to one, then multiply by 100 Procrastinating Pats

array([16.        ,  5.33333333, 40.        , 25.33333333,  0.        ,
       13.33333333])

We can see from this list, the number of Ps that we expect to find on each website after long times.
Putting them in order of *popularity* (based on this metric), the PageRank of this micro-internet is:

**C**, **D**, **A**, **F**, **B**, **E**

Referring back to the micro-internet diagram, is this what you would have expected?
Convince yourself that based on which pages seem important given which others link to them, that this is a sensible ranking.

Let's now try to get the same result using the Power-Iteration method that we covered in the class.
This method will be much better at dealing with large systems.

First let's set up our initial vector, $\mathbf{r}^{(0)}$, so that we have our 100 Ps equally distributed on each of our 6 websites.

In [39]:
r = 100 * np.ones(6) / 6 # Sets up this vector (6 entries of 1/6 × 100 each)
r # Shows it's value

array([16.66666667, 16.66666667, 16.66666667, 16.66666667, 16.66666667,
       16.66666667])

Next, let's update the vector to the next minute, with the matrix $L$.
Run the following cell multiple times, until the answer stabilises.

In [40]:
r = L @ r # Apply matrix L to r
r # Show it's value
# Re-run this cell multiple times to converge to the correct answer.

array([13.88888889, 13.88888889, 38.88888889, 27.77777778,  0.        ,
        5.55555556])

We can automate applying this matrix multiple times as follows,

In [41]:
r = 100 * np.ones(6) / 6 # Sets up this vector (6 entries of 1/6 × 100 each)
for i in np.arange(100) : # Repeat 100 times
    r = L @ r
r

array([16.        ,  5.33333333, 40.        , 25.33333333,  0.        ,
       13.33333333])

Or even better, we can keep running until we get to the required tolerance.

In [42]:
r = 100 * np.ones(6) / 6 # Sets up this vector (6 entries of 1/6 × 100 each)
lastR = r
r = L @ r
i = 0
while la.norm(lastR - r) > 0.01 :
    lastR = r
    r = L @ r
    i += 1
print(str(i) + " iterations to convergence.")
r

18 iterations to convergence.


array([16.00149917,  5.33252025, 39.99916911, 25.3324738 ,  0.        ,
       13.33433767])

See how the PageRank order is established fairly quickly, and the vector converges on the value we calculated earlier after a few tens of repeats.

### Damping Parameter
The system we just studied converged fairly quickly to the correct answer.
Let's consider an extension to our micro-internet where things start to go wrong.

Say a new website is added to the micro-internet: *G* Website.
This website is linked to by *FaceSpace* and only links to itself.
![An Expanded Micro-Internet](internet_2.png "An Expanded Micro-Internet")

Intuitively, only *F*, which is in the bottom half of the page rank, links to this website amongst the two others it links to,
so we might expect *G* site to have a correspondingly low PageRank score.

Build the new $L$ matrix for the expanded micro-internet, and use Power-Iteration.

In [43]:
 # We'll call this one L2, to distinguish it from the previous L.
L2 = np.array([[0,   1/2, 1/3,  0,  0,      0, 0],
              [1/3,  0,   0,    0,  1/2,    0, 0],   
              [1/3,  1/2, 0,    1,  0,    1/3, 0],
              [1/3,  0,   1/3,  0,  1/2,  1/3, 0],
              [0,    0,   0,    0,  0,      0, 0],
              [0,    0,   1/3,  0,  0,      0, 0],
              [0,    0,   0,    0,  0,    1/3, 1]])

In [44]:
r = 100 * np.ones(7) / 7 # Sets up this vector (6 entries of 1/6 × 100 each)
lastR = r
r = L2 @ r
i = 0
while la.norm(lastR - r) > 0.01 :
    lastR = r
    r = L2 @ r
    i += 1
print(str(i) + " iterations to convergence.")
r

131 iterations to convergence.


array([3.04699778e-02, 1.06432333e-02, 7.12661184e-02, 4.42319808e-02,
       0.00000000e+00, 2.48934190e-02, 9.98184953e+01])

In [45]:
d = 0.5 # Feel free to play with this parameter after running the code once.
M = d * L2 + (1-d)/7 * np.ones([7, 7]) # np.ones() is the J matrix, with ones for each entry.

In [46]:
r = 100 * np.ones(7) / 7 # Sets up this vector (6 entries of 1/6 × 100 each)
lastR = r
r = M @ r
i = 0
while la.norm(lastR - r) > 0.01 :
    lastR = r
    r = M @ r
    i += 1
print(str(i) + " iterations to convergence.")
r

8 iterations to convergence.


array([13.68217054, 11.20902965, 22.41964343, 16.7593433 ,  7.14285714,
       10.87976354, 17.90719239])


# Produce a function that can calculate the PageRank for an arbitrarily large probability matrix.


In [47]:
# Input link matrix L (which can be generated using the code given below) and damping factor d.
def pageRank(L, d) :
   
    M = d * L + (1-d)/7 * np.ones([7, 7]) 
    r = 100 * np.ones(7) / 7 
    lastR = r
    r = M @ r
    i = 0
    while la.norm(lastR - r) > 0.01 :
        lastR = r
        r = M @ r
        i += 1
    print(str(i) + " iterations to convergence.")
    
    return r
    


In [48]:
#generatea random internet links
def generate_link(n) :
    c = np.full([n,n], np.arange(n))
    c = (abs(np.random.standard_cauchy([n,n])/2) > (np.abs(c - c.T) + 1))+0
    c = (c+1e-10) / np.sum((c+1e-10), axis=0)
    return c

In [51]:
# Use the following function to generate internets of different sizes.
generate_link(2)

array([[0.5, 0.5],
       [0.5, 0.5]])

In [52]:
# Test your PageRank method against the built in "eig" method.
L = generate_link(7)

In [53]:
pageRank(L, .5)

6 iterations to convergence.


array([13.04445803,  8.69599524, 17.39088787, 23.18558944, 17.39088787,
        8.69599524, 11.5961863 ])

In [16]:
# using eigen vectors as seen before.
eVals, eVecs = la.eig(L) # Gets the eigenvalues and vectors
order = np.absolute(eVals).argsort()[::-1] # Orders them by their eigenvalues
eVals = eVals[order]
eVecs = eVecs[:,order]

r = eVecs[:, 0]
100 * np.real(r / np.sum(r))

array([ 4.54545455, 18.18181818,  4.54545455,  9.0909091 , 27.27272727,
       15.15151515, 21.21212121])

In [17]:
#your answers do not match always. Why?

In [ ]:
#Due to the fact that the eig method does not always converge the same value